[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then"
position = "before"
match_indent = true
payload = '''
    -- Check if we are playing the Evil Egg Deck
    if G.GAME.selected_back and G.GAME.selected_back.effect.center.key == 'b_smsn_evilegg' then
        if v.key == 'j_smsn_tasteful' then
            -- FORCE ADD: Ignore rarity, ignore bans, just put it in the pool.
            add = true
        else
            -- BAN EVERYTHING ELSE
            add = false
        end
    end
'''